Category.destroy_all

frontend = Category.create!(name: 'Front-end')
backend = Category.create!(name: 'Back-end')
database = Category.create!(name: 'Banco de Dados')
devops = Category.create!(name: 'DevOps & Infra')
arquitetura = Category.create!(name: 'Arquitetura de Software')
mobile = Category.create!(name: 'Mobile')
testes = Category.create!(name: 'Testes')
ux_ui = Category.create!(name: 'UX/UI')

links = [
  # Front‑end
  { title: 'Documentação oficial do Angular', url: 'https://angular.dev/', description: 'Documentação completa e oficial do framework Angular.', category: frontend },
  { title: 'Documentação React', url: 'https://react.dev/', description: 'Boas práticas e guia oficial do React.', category: frontend },
  { title: 'Vue.js Style Guide', url: 'https://vuejs.org/style-guide/', description: 'Padrões de escrita de código Vue recomendados.', category: frontend },
  { title: 'Blog da Alura: boas práticas CSS', url: 'https://blog.alura.com.br/boas-praticas-css/', description: 'Organização, modularidade e performance em CSS.', category: frontend },
  { title: 'Alura: performance web com Front‑End', url: 'https://blog.alura.com.br/performance-web-frontend/', description: 'Como otimizar o carregamento e renderização de páginas.', category: frontend },
  { title: 'Post LinkedIn: Styled Components dicas', url: 'https://pt.linkedin.com/posts/daniel-de‑oliveira‑mo%C3%A7o_styledcomponents‑javascript‑react‑…', description: 'Dicas práticas para dominar Styled Components em React.', category: frontend },
  { title: 'Post LinkedIn: acessibilidade com React', url: 'https://pt.linkedin.com/posts/tiago‑torquato‑acessibilidade‑react‑interfaces‑inclusivas‑…', description: 'Princípios WCAG, ARIA e HTML semântico para acessibilidade.', category: frontend },
  { title: 'LinkedIn: portfólio HTML‑CSS Figma', url: 'https://pt.linkedin.com/posts/marianamedrano_o‑bom‑de‑aprender‑front‑end‑portfolio‑…', description: 'Exemplo de workflow: protótipo no Figma e implementação em HTML/CSS.', category: frontend },
  { title: 'LinkedIn: alunos Alura e Next.js', url: 'https://pt.linkedin.com/posts/aluracursos_alurainspira‑nextjs‑aprendizagem‑…', description: 'Experiência real com projetos em Next.js SSG, SSR e Prisma.', category: frontend },
  { title: 'MDN web docs: JavaScript best practices', url: 'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Best_practices', description: 'Guia de boas práticas JavaScript da MDN.', category: frontend },
  { title: 'CSS Tricks: melhores práticas CSS modernas', url: 'https://css-tricks.com/guides/', description: 'Artigos sobre flexbox, grid, performance e organização.', category: frontend },
  { title: 'Smashing Magazine: front‑end workflow', url: 'https://www.smashingmagazine.com/category/front-end/', description: 'Técnicas modernas de build, otimização e modularização.', category: frontend },
  { title: 'A11Y Projeto: acessibilidade web', url: 'https://a11yproject.com/', description: 'Recursos e padrões para tornar sites acessíveis.', category: frontend },
  { title: 'Post LinkedIn: SASS e modularização CSS', url: 'https://pt.linkedin.com/posts/gustavo‑gantois_front-end‑sass‑modular‑…', description: 'Uso de SASS com variáveis, mixins e modular CSS.', category: frontend },
  { title: 'Post LinkedIn: React + Tailwind + animações', url: 'https://pt.linkedin.com/posts/gustavo‑gantois_front‑end‑tailwind‑css‑…', description: 'Combinação de ferramentas modernas para interfaces.', category: frontend },
  { title: 'Alura: frameworks modernos JS', url: 'https://blog.alura.com.br/front-end-frameworks-populares/', description: 'Comparativo de React, Vue, Angular e quando usar cada um.', category: frontend },
  { title: 'Dev.to: estrutura de projetos front‑end', url: 'https://dev.to/t/frontend', description: 'Padrões e convenções para organizar projetos front‑end.', category: frontend },
  { title: 'LinkedIn: aprendizado de componentes front‑end', url: 'https://pt.linkedin.com/posts/caio‑prates_front‑component‑learning‑…', description: 'Desenvolvimento com React, componentes reutilizáveis e CSS‑in‑JS.', category: frontend },
  { title: 'Alura: responsividade e acessibilidade UI', url: 'https://blog.alura.com.br/responsividade-acessibilidade-ui', description: 'Como implementar responsividade e contraste para inclusão.', category: frontend },
  { title: 'Web.dev do Google: performance e acessibilidade', url: 'https://web.dev/', description: 'Ferramentas e auditorias para sites rápidos e acessíveis.', category: frontend },

  # Back‑end 
  { title: 'Blog da Alura: segurança em API REST', url: 'https://blog.alura.com.br/seguranca-api-rest/', description: 'Autenticação, criptografia e validação de payload.', category: backend },
  { title: 'Documentação oficial do Spring Boot', url: 'https://spring.io/projects/spring-boot', description: 'Melhores práticas para backend em Java.', category: backend },
  { title: 'Documentação oficial do Django', url: 'https://www.djangoproject.com/start/', description: 'Padrões de segurança e arquitetura no Django.', category: backend },
  { title: 'LinkedIn: clean code backend', url: 'https://pt.linkedin.com/posts/william_boaspraticas-cleancode-backend', description: 'Código limpo, modularidade e testes automatizados.', category: backend },
  { title: 'GitHub: padrões RESTful APIs', url: 'https://github.com/restfulapi', description: 'Exemplos e guidelines para design de APIs.', category: backend },
  { title: 'Alura: microserviços com Spring Cloud', url: 'https://blog.alura.com.br/microservices-spring-cloud/', description: 'Arquitetura distribuída, resiliência e mensageria.', category: backend },
  { title: 'LinkedIn: Clean Architecture e MVC', url: 'https://pt.linkedin.com/posts/paulo-do-monte_cleanarchitecture-mvc-backend', description: 'Reflexões sobre padrões arquiteturais no backend.', category: backend },
  { title: 'OWASP: top 10 vulnerabilidades', url: 'https://owasp.org/www-project-top-ten/', description: 'Guia de vulnerabilidades e mitigação em aplicações web.', category: backend },
  { title: 'Blog da Alura: autenticação JWT', url: 'https://blog.alura.com.br/jwt-autenticacao-api/', description: 'Como usar JWT com segurança e renovação de tokens.', category: backend },
  { title: 'Post LinkedIn: testes automatizados com Java', url: 'https://br.linkedin.com/in/gabrieltsr', description: '“automatizando testes com Java” no backend Alura.', category: backend },
  { title: 'Django REST framework: melhores práticas', url: 'https://www.django-rest-framework.org/', description: 'Views, serializers e segurança em APIs Django.', category: backend },
  { title: 'Node.js Best Practices', url: 'https://github.com/goldbergyoni/nodebestpractices', description: 'Repositório com padrões de projeto Node.js.', category: backend },
  { title: 'Spring Security best practices', url: 'https://spring.io/projects/spring-security', description: 'Mecanismos de autenticação e autorização.', category: backend },
  { title: 'Blog da Alura: Docker no backend', url: 'https://blog.alura.com.br/docker-java-backend/', description: 'Containerização de backend com Docker.', category: backend },
  { title: 'Post LinkedIn: testes backend Jest', url: 'https://pt.linkedin.com/posts/marcele‑montalv%C3%A3o‑testes‑automatizados‑jest‑…', description: 'Boas práticas com Jest para backend.', category: backend },
  { title: 'Alura: versionamento de APIs', url: 'https://blog.alura.com.br/versionamento-api-rest/', description: 'Como versionar e evoluir APIs sem quebrar clientes.', category: backend },
  { title: 'Martin Fowler: guia de arquitetura de backend', url: 'https://martinfowler.com/', description: 'Padrões de integração, arquitetura hexagonal etc.', category: backend },
  { title: 'Documentação oficial GraphQL', url: 'https://graphql.org/learn/', description: 'API moderna e boas práticas de GraphQL.', category: backend },
  { title: 'Post LinkedIn: backend React‑API‑FastAPI', url: 'https://pt.linkedin.com/in/kasiliana-oliveira', description: 'Desenvolvimento web com React no front e FastAPI backend.', category: backend },
  { title: 'Alura: testes automatizados backend', url: 'https://blog.alura.com.br/testes-automatizados-backend/', description: 'Unidade, integração e TDD para backend.', category: backend },

  # Banco de Dados
  { title: 'Blog da Alura: modelagem MongoDB', url: 'https://blog.alura.com.br/mongodb-modelagem-indices', description: 'Modelagem e índices em banco NoSQL.', category: database },
  { title: 'Blog da Alura: desempenho SQL', url: 'https://blog.alura.com.br/desempenho-sql/', description: 'Otimização de consultas, índices e cache.', category: database },
  { title: 'PostgreSQL official documentation', url: 'https://www.postgresql.org/docs/', description: 'Boas práticas e tuning em PostgreSQL.', category: database },
  { title: 'MySQL performance tuning', url: 'https://dev.mysql.com/doc/refman/en/optimization.html', description: 'Guia oficial de otimização do MySQL.', category: database },
  { title: 'MongoDB official docs schema design', url: 'https://www.mongodb.com/docs/manual/core/data-modeling-introduction/', description: 'Abordagem formal para modelagem NoSQL.', category: database },
  { title: 'Alura: SQL vs NoSQL comparativo', url: 'https://blog.alura.com.br/sql-vs-nosql/', description: 'Quando usar cada tipo de banco e trade‑offs.', category: database },
  { title: 'LinkedIn: boas práticas DB', url: 'https://pt.linkedin.com/posts/priscila-nascimento_fullstack-java-sql-nosql‑…', description: 'Experiência com bancos relacionais e NoSQL.', category: database },
  { title: 'Normalization explained', url: 'https://www.essentialsql.com/get-ready-to-learn-sql-database-normalization-basics/', description: 'Formas normais e organização relacional.', category: database },
  { title: 'Use The Index, Luke!', url: 'https://use-the-index-luke.com/', description: 'Técnicas práticas para índices eficientes.', category: database },
  { title: 'DataDog: monitoramento de bancos', url: 'https://www.datadoghq.com/blog/database-performance-monitoring/', description: 'Observabilidade de performance e logs.', category: database },
  { title: 'Alura: backup e recuperação em BD', url: 'https://blog.alura.com.br/backup-banco-dados/', description: 'Procedimentos de backup e disaster recovery.', category: database },
  { title: 'MongoDB University courses', url: 'https://university.mongodb.com/', description: 'Cursos gratuitos sobre administração e modelagem.', category: database },
  { title: 'Oracle Database concepts guide', url: 'https://docs.oracle.com/en/database/', description: 'Arquitetura e otimização em Oracle.', category: database },
  { title: 'LinkedIn: performance em consultas SQL', url: 'https://pt.linkedin.com/posts/alura‑cursos_sql‑desempenho‑…', description: 'Query tuning e boas práticas de índices.', category: database },
  { title: 'Google BigQuery best practices', url: 'https://cloud.google.com/bigquery/docs/best-practices-intro', description: 'Análise de dados em larga escala.', category: database },
  { title: 'NoSQL data modeling patterns', url: 'https://www.mongodb.com/patterns', description: 'Padrões de dados noSQL: polls, trees, adjacency list etc.', category: database },
  { title: 'Alura: normalização e modelagem SQL', url: 'https://blog.alura.com.br/modelagem-banco-dados-sql/', description: 'Passo a passo para um bom design relacional.', category: database },
  { title: 'Redis use cases and practices', url: 'https://redis.io/docs/getting-started/', description: 'Cache, pub/sub e performance com Redis.', category: database },

  # DevOps & Infra
  { title: 'O que é DevOps? Guia introdutório Alura', url: 'https://www.alura.com.br/artigos/devops-o-que-e', description: 'Cultura, ferramentas e hábitos de DevOps para iniciantes.', category: devops },
  { title: 'Guia completo sobre a cultura DevOps Alura', url: 'https://www.alura.com.br/artigos/o-que-e-devops', description: 'Transformação do desenvolvimento por DevOps e seus benefícios.', category: devops },
  { title: 'Governança de TI para operações DevOps', url: 'https://pt.wikipedia.org/wiki/Governan%C3%A7a_de_TI_para_Opera%C3%A7%C3%B5es_de_DevOps', description: 'Equilíbrio entre automação e compliance.', category: devops },
  { title: 'Boas práticas de DevOps: guia explicativo', url: 'https://enotas.com.br/blog/devops/', description: 'Práticas recomendadas e cultura DevOps no mundo real.', category: devops },
  { title: 'Alura Imersão DevOps e Cloud (Google)', url: 'https://guiadeti.com.br/noticias/imersao-em-devops-e-cloud-gratuita-alura-google', description: 'Pipeline CI/CD, Docker, deploy em cloud real com práticas seguras.', category: devops },
  { title: 'Vídeo: o que é DevOps? #AluraMais', url: 'https://www.youtube.com/watch?v=3_k2GVkMt30', description: 'Explicação clara sobre cultura, processos e ferramentas DevOps.', category: devops },
  { title: 'Vídeo: aprender DevOps em 40 minutos Alura', url: 'https://www.youtube.com/watch?v=ni2xJQG8hDg', description: 'Resumo ágil da implementação de DevOps para iniciantes.', category: devops },
  { title: 'DevOps: {Des}complicado?!', url: 'https://medium.com/dados-para-todos/devops-des-complicado-51bb80dd2144', description: 'Abordagem acessível da AWS sobre cultura, ferramentas e velocidade.', category: devops },
  { title: 'FinOps: gestão de custos em cloud', url: 'https://www.alura.com.br/artigos/finops-entenda-sua-importancia', description: 'Estratégias para otimizar custo e governança em nuvem.', category: devops },
  { title: 'Kubernetes: como usá-lo para gerenciar aplicações', url: 'https://www.alura.com.br/artigos/kubernetes-como-usar', description: 'Plataforma orquestradora e boas práticas em produção.', category: devops },
  { title: 'DevSecOps: security-first em pipelines', url: 'https://www.alura.com.br/artigos/devsecops', description: 'Integrando segurança em cada etapa do pipeline CI/CD.', category: devops },
  { title: 'Back‑End: guia para iniciar na área (inclui práticas DevOps)', url: 'https://www.alura.com.br/artigos/back-end-guia-iniciar', description: 'Conexão entre backend e práticas de infraestrutura ágil.', category: devops },
  { title: 'Cibersegurança: guia para iniciantes DevOps', url: 'https://www.alura.com.br/artigos/ciberseguranca', description: 'Proteção de pipelines, acessos e dados sensíveis.', category: devops },
  { title: 'Rede de computadores: guia completo para DevOps', url: 'https://www.alura.com.br/artigos/rede-de-computadores', description: 'Fundamentos de redes aplicados à infraestrutura automatizada.', category: devops },
  { title: 'O que é Gateway e como facilita na comunicação', url: 'https://www.alura.com.br/artigos/o-que-e-gateway', description: 'API Gateway e roteamento em ambientes distribuídos.', category: devops },
  { title: 'Vídeo: Aproveite a Imersão DevOps Alura+Google', url: 'https://www.youtube.com/watch?v=gP673lGrQks', description: 'Dicas práticas para quem começou a imersão DevOps.', category: devops },
  { title: 'Boas práticas Docker no backend', url: 'https://blog.alura.com.br/docker-java-backend/', description: 'Containerização segura e eficiente de aplicações.', category: devops },
  { title: 'Pipelines CI/CD com React Native (Alura)', url: 'https://blog.alura.com.br/cicd-react-native', description: 'Integração e entrega contínua aplicadas a apps mobile.', category: devops },
  { title: 'Back‑End + CI/CD + testes automatizados', url: 'https://blog.alura.com.br/testes-automatizados-backend', description: 'Como orquestrar pipelines com testes e deploy automatizado.', category: devops },
  { title: 'Boas‑vindas HipstersPontoTube Dev Full‑Stack (Atua DevOps)', url: 'https://www.youtube.com/watch?v=p5sjmV0_Yto', description: 'Visão geral de habilidades full‑stack incluindo DevOps.', category: devops },

  # Arquitetura de Software (20)
  { title: 'Padrões arquiteturais: arquitetura de software descomplicada', url: 'https://www.alura.com.br/artigos/padroes-arquiteturais-arquitetura-software-descomplicada', description: 'Normas, princípios e padrões de arquitetura moderna.', category: arquitetura },
  { title: 'Post LinkedIn: Well‑Architected Framework AWS', url: 'https://www.linkedin.com/posts/hiltonpinto_aws-well-architected-framework-activity-7189988992610693121-8gRi', description: 'Reflexões sobre boas práticas do Well‑Architected AWS.', category: arquitetura },
  { title: 'Boas práticas em arquitetura de software (blog UDS)', url: 'https://uds.com.br/blog/boas-praticas-em-arquitetura-de-software', description: 'Performance, escalabilidade, observabilidade e manutenibilidade.', category: arquitetura },
  { title: 'Wikipedia: Service‑oriented architecture (SOA)', url: 'https://pt.wikipedia.org/wiki/Service-oriented_architecture', description: 'Conceitos e princípios de arquitetura orientada a serviços.', category: arquitetura },
  { title: 'Wikipedia: Arquitetura multicamada', url: 'https://pt.wikipedia.org/wiki/Arquitetura_multicamada', description: 'Separação clara de camadas e responsabilidades.', category: arquitetura },
  { title: 'Vídeo: criar arquiteturas que crescem com negócio', url: 'https://www.youtube.com/watch?v=VyMnBvaiU-E', description: 'Orientações práticas sobre arquitetura escalável.', category: arquitetura },
  { title: 'Vídeo: Arquitetura de sistemas com Fabio Akita', url: 'https://www.youtube.com/watch?v=oedWxgAZc2A', description: 'Discussão sobre arquitetura, identidade e evolução do sistema.', category: arquitetura },
  { title: 'Livro: Arquitetura de software distribuído (Casa do Código)', url: 'https://www.casadocodigo.com.br/products/livro-arquitetura-software-distribuido', description: 'Projeto de microsserviços e padrões de integração.', category: arquitetura },
  { title: 'Post LinkedIn: integração e longevidade na arquitetura', url: 'https://pt.linkedin.com/pulse/arquitetura-de-software-integra%C3%A7%C3%A3o-e-longevidade-nas-solu%C3%A7%C3%B5es-lopes-rqbxf', description: 'Divisão de camadas e clareza estrutural em projetos.', category: arquitetura },
  { title: 'Alura: Clean Architecture, DDD e SOLID', url: 'https://www.alura.com.br/artigos/arquitetura-software-design-de-aplicacao', description: 'Aplicação de SOLID, DDD e padrões de projetos em arquitetura.', category: arquitetura },
  { title: 'Martin Fowler: princípios e patterns', url: 'https://martinfowler.com/', description: 'Padrões clássicos de arquitetura e integração de sistema.', category: arquitetura },
  { title: 'Well‑Architected Framework AWS (blog Alura)', url: 'https://www.alura.com.br/artigos/aws-well-architected', description: 'Framework AWS aplicado em arquitetura robusta e segura.', category: arquitetura },
  { title: 'Wiki: arquitetura orientada a eventos (event‑driven)', url: 'https://en.wikipedia.org/wiki/Event-driven_architecture', description: 'Design para sistemas reativos e desacoplados.', category: arquitetura },
  { title: 'Alura Imersão DevOps: arquitetura de sistema em cloud', url: 'https://guiadeti.com.br/noticias/imersao-em-devops-e-cloud-gratuita-alura-google', description: 'Tópicos práticos sobre deployment, escalabilidade e infraestrutura.', category: arquitetura },
  { title: 'Padrões de API RESTful e arquitetura', url: 'https://github.com/restfulapi', description: 'Exemplos de design e integração de sistemas via API.', category: arquitetura },
  { title: 'Vídeo: Clean Code e SOLID (arquitetura fim‑a‑fim)', url: 'https://www.youtube.com/watch?v=MwoA-pzzAQw', description: 'Importância de arquitetura limpa e princípios de código.', category: arquitetura },
  { title: 'Alura: microserviços com Spring Cloud', url: 'https://blog.alura.com.br/microservices-spring-cloud', description: 'Padrões distribuídos, resiliência e mensageria.', category: arquitetura },
  { title: 'Alura: Docker e infraestrutura limpa', url: 'https://blog.alura.com.br/docker-java-backend', description: 'Infraestrutura como código para arquiteturas robustas.', category: arquitetura },
  { title: 'Alura: testes automatizados e arquitetura', url: 'https://blog.alura.com.br/testes-automatizados-backend', description: 'Arquitetura testável com integração e TDD.', category: arquitetura },

  # Mobile (20)
  { title: 'Alura: React Native guia para publicar app', url: 'https://www.alura.com.br/artigos/react-native-publicar-aplicativo', description: 'Como publicar apps React Native com melhores práticas.', category: mobile },
  { title: 'Alura: Padrões de navegação React Native', url: 'https://www.alura.com.br/artigos/padroes-navegacao-react-native', description: 'Stacks, tabs e drawer com boas práticas UX e técnico.', category: mobile },
  { title: 'Alura: CI/CD para React Native', url: 'https://blog.alura.com.br/cicd-react-native', description: 'Integração e entrega contínua aplicada a apps móveis.', category: mobile },
  { title: 'Princípios UX para apps móveis', url: 'https://blog.onedaytesting.com.br/7-principios-de-ux-para-apps-moveis-que-voce-deveria-conhecer', description: 'Recomendações de usabilidade específicas para mobile.', category: mobile },
  { title: 'Zoom de imagens mobile sem prejudicar performance', url: 'https://cursos.alura.com.br/forum/topico-boas-praticas-de-zoom-ou-ampliacao-de-imagens-em-mobile-181292', description: 'Implementando zoom acessível e performático.', category: mobile },
  { title: 'Artigos Alura: Mobile (busca)', url: 'https://www.alura.com.br/artigos?categories=Mobile', description: 'Coleção de artigos sobre boas práticas em mobile.', category: mobile },
  { title: 'Start Alura Mobile-first e design responsivo', url: 'https://www.alura.com.br/artigos/design-tokens-acessibilidade', description: 'Tokens de design, responsividade e acessibilidade.', category: mobile },
  { title: 'Kotlin e arquitetura mobile moderna (Alura)', url: 'https://blog.alura.com.br/kotlin-android-boa-pratica', description: 'Padrões e boas práticas para Android com Kotlin.', category: mobile },
  { title: 'Boas práticas em Flutter (Alura blog)', url: 'https://blog.alura.com.br/flutter-boas-praticas', description: 'Frameworks, widgets e performance em Flutter.', category: mobile },
  { title: 'UX/UI mobile: acessibilidade e usabilidade', url: 'https://www.alura.com.br/artigos/usabilidade-acessibilidade-produtos-digitais', description: 'Boas práticas aplicadas à interface mobile.', category: mobile },
  { title: 'Teste de usabilidade em app mobile (Alura)', url: 'https://www.alura.com.br/artigos/testes-automatizados-mobile', description: 'Estratégias de testes e validação do usuário.', category: mobile },
  { title: 'Post LinkedIn: CI/CD em app React Native', url: 'https://pt.linkedin.com/posts/aluracursos_alurainspira-nextjs-aprendizagem', description: 'Exemplo real de pipeline mobile em rede profissional.', category: mobile },
  { title: 'Vídeo: guia Dev Full‑Stack inclui mobile', url: 'https://www.youtube.com/watch?v=p5sjmV0_Yto', description: 'Caminho full-stack com práticas mobile integradas.', category: mobile },
  { title: 'Conteúdo Alura: Mobile (filtros)', url: 'https://www.alura.com.br/artigos?categories=Mobile', description: 'Atualizações frequentes de conteúdo mobile.', category: mobile },

  # Testes
  { title: 'Testes automatizados: como melhorar qualidade e confiabilidade', url: 'https://www.alura.com.br/artigos/testes-automatizados', description: 'Tipos de testes, melhores práticas e frameworks.', category: testes },
  { title: 'Boas práticas em testes automatizados', url: 'https://reiload-88128.medium.com/boas-práticas-em-testes-automatizados-612b47831c50', description: 'Estrutura, clareza e automação eficiente.', category: testes },
  { title: 'Melhores práticas de testes de software (ESR)', url: 'https://esr.rnp.br/desenvolvimento-de-sistemas/melhores-praticas-em-testes-de-software', description: 'Clareza de testes, integração CI/CD e manutenção.', category: testes },
  { title: '7 boas práticas em automação de testes', url: 'https://auditeste.com.br/boas-praticas-em-automacao-de-testes', description: 'Estratégia clara, escolha de ferramentas, scripts eficientes.', category: testes },
  { title: 'TDD | Caelum', url: 'https://tdd.caelum.com.br/', description: 'Importância dos testes automatizados contínuos no dia a dia.', category: testes },
  { title: 'Artigo Alura: automatizando testes com Java', url: 'https://www.alura.com.br/conteudo/boas-praticas-programacao-testes-java', description: 'Escrevendo testes automatizados com JUnit e Mockito.', category: testes },
  { title: 'Melhores práticas de automação: revisão literária acadêmica', url: 'https://arxiv.org/abs/2202.09076', description: 'Revisão de 26 práticas para maturidade em automação.', category: testes },
  { title: 'Post LinkedIn: dicas para automação de testes (Pedro Azevedo)', url: 'https://pt.linkedin.com/posts/pedroazevedoteixeira_qa-qualityassurance-automacaodetestes-activity-7287076402749657089-wifJ', description: 'Uso de APIs divertidas para treino prático em automação.', category: testes },
  { title: 'Artigo Alura: testes automatizados backend', url: 'https://blog.alura.com.br/testes-automatizados-backend', description: 'TDD, integração, teste de unidade e pipelines.', category: testes },
  { title: 'Post LinkedIn: experiência com Jest para backend', url: 'https://pt.linkedin.com/posts/marcele-montalv%C3%A3o-testes-automatizados-jest-activity', description: 'Práticas com Jest e cobertura de teste em backend.', category: testes },
  { title: 'Post LinkedIn: testes unitários Front‑end', url: 'https://pt.linkedin.com/posts/gabrielle-vieira-porto_5-ideias-de-projetos-para-front-end-iniciantes-activity-7284317362441383936-TyIL', description: 'Projetos front com testes, ARIA, Grid/Flex e acessibilidade.', category: testes },
  { title: 'Como melhorar qualidade com testes automatizados', url: 'https://www.alura.com.br/artigos/testes-automatizados', description: 'Benefícios, tipos e ferramentas de testes automatizados.', category: testes },
  { title: 'Article: importância de testes claros e legíveis', url: 'https://esr.rnp.br/desenvolvimento-de-sistemas/melhores-praticas-em-testes-de-software', description: 'Nomes descritivos e modularidade nos scripts de teste.', category: testes },
  { title: 'Estratégia CI/CD com automação de testes', url: 'https://auditeste.com.br/boas-praticas-em-automacao-de-testes', description: 'Integre testes ao pipeline CI/CD desde o início.', category: testes },
  { title: 'Testes automatizados com UI/Backend e CI/CD', url: 'https://blog.alura.com.br/testes-automatizados-backend', description: 'Coordenação de teste e deploy automatizado.', category: testes },
  { title: 'TDD e qualidade em testes contínuos (Caelum)', url: 'https://tdd.caelum.com.br/', description: 'Rotina de testes automatizados no desenvolvimento.', category: testes },
  { title: 'Pesquisa acadêmica sobre maturidade em automação', url: 'https://arxiv.org/abs/2202.09076', description: 'Melhores práticas validadas por literatura.', category: testes },
  { title: 'Post LinkedIn com dicas práticas de APIs para testar', url: 'https://pt.linkedin.com/posts/pedroazevedoteixeira_qa-qualityassurance-automacaodetestes-activity-7287076402749657089-wifJ', description: 'Sugestão de APIs para prática de automação.', category: testes },
  { title: 'Manual prático de boas práticas em automação', url: 'https://reiload-88128.medium.com/boas-práticas-em-testes-automatizados-612b47831c50', description: 'Agilidade e estrutura no desenvolvimento de testes.', category: testes },
  { title: 'Revisão sobre clareza e manutenção de testes', url: 'https://esr.rnp.br/desenvolvimento-de-sistemas/melhores-praticas-em-testes-de-software', description: 'Testes com documentação e legibilidade clara.', category: testes },

  # UX/UI
  { title: '5 regras para um bom UI', url: 'https://www.alura.com.br/artigos/5-regras-um-bom-ui', description: 'Simplicidade, hierarquia, consistência, cores e boas práticas.', category: ux_ui },
  { title: 'UX Design: o que é, profissões e guia para iniciar', url: 'https://www.alura.com.br/artigos/ux-design', description: 'Por que estudar UX antes da UI e fundamentos do design.', category: ux_ui },
  { title: 'UI Design: interface e Motion Design', url: 'https://www.alura.com.br/artigos/ui-design', description: 'Como animações melhoram usabilidade e comunicação visual.', category: ux_ui },
  { title: 'UX e UI para a terceira idade', url: 'https://www.alura.com.br/artigos/ux-ui-terceira-idade', description: 'Design inclusivo para idosos: navegação e clareza.', category: ux_ui },
  { title: 'Boas práticas de documentação de Design System', url: 'https://www.alura.com.br/artigos/boas-praticas-documentacao-design-system', description: 'Como documentar componentes e padrões efetivamente.', category: ux_ui },
  { title: 'Guia completo: como começar em UX Design', url: 'https://brasil.uxdesign.cc/guia-completo-como-começar-em-ux-design-bd21b9f23b8', description: 'Etapas práticas para iniciar na área de UX.', category: ux_ui },
  { title: 'Melhores práticas de UX Design (LinkedIn)', url: 'https://pt.linkedin.com/pulse/melhores-práticas-de-ux-design-direto-ao-ponto-thomaz-braga-scheider', description: 'Acessibilidade, formulários, iconografia, fontes sistemáticas.', category: ux_ui },
  { title: 'Post LinkedIn: boas práticas de UI pra iniciantes (Thais Harumi)', url: 'https://pt.linkedin.com/posts/thaisharumioshiro_boas-práticas-de-ui-pra-iniciantes-em-1-activity-7256796389781716993-DQ03', description: 'Detalhes visuais que fazem a diferença em interfaces.', category: ux_ui },
  { title: 'Livro: Introdução e Boas Práticas em UX Design', url: 'https://cursos.alura.com.br/forum/topico-introducao-e-boas-praticas-em-ux-design-280596', description: 'Leitura recomendada para quem está começando em UX.', category: ux_ui },
  { title: 'Outro post Alura sobre esse livro de UX Design', url: 'https://cursos.alura.com.br/forum/topico-introducao-e-boas-praticas-em-ux-design-143570', description: 'Discussão e recomendações para aprofundar no UX.', category: ux_ui },
  { title: 'Dicas práticas de UX/UI para iniciantes (vídeo)', url: 'https://www.youtube.com/watch?v=Fwu4pWcTGFo', description: 'Guideline com 5 dicas para começar no UX/UI.', category: ux_ui },
  { title: 'Design de interação e princípios CRAP (Wiki UX)', url: 'https://pt.wikipedia.org/wiki/Experi%C3%AAncia_do_usu%C3%A1rio', description: 'Contraste, repetição, alinhamento e proximidade.', category: ux_ui },
  { title: 'Incluir UX designers nas redes sociais (Medium UXDesign.br)', url: 'https://brasil.uxdesign.cc/como-começar-em-ux-design-um-guia-completo-875db8cc3b4', description: 'Conectar-se com profissionais de design e conteúdo.', category: ux_ui },
  { title: 'Melhores práticas de design para mídias sociais', url: 'https://www.alura.com.br/artigos/5-melhores-praticas-design-midias-sociais', description: 'Legibilidade, consistência e otimização mobile.', category: ux_ui },
  { title: 'Curso UI Design: padrões para aplicativos móveis', url: 'https://www.alura.com.br/curso-online-ui-design-experiencia-app-ui-patterns', description: 'Padrões UI para mobile e navegação intuitiva.', category: ux_ui },
  { title: 'Documentação robusta de design system é boa prática', url: 'https://www.alura.com.br/artigos/boas-praticas-documentacao-design-system', description: 'Reuso, regras e uso claro de um Design System.', category: ux_ui },
  { title: 'Post LinkedIn: comece seu LinkedIn para UX/UI fora', url: 'https://pt.linkedin.com/posts/vitorferrara_%C3%A9-uiuxproduct-designer-e-quer-trabalhar-activity-7290832441424924928768-UlWs', description: 'Case: prepare perfil e portfólio para mercado internacional.', category: ux_ui },
  { title: 'Livro recomendado para UX: Fabrício Teixeira', url: 'https://cursos.alura.com.br/forum/topico-introducao-e-boas-praticas-em-ux-design-280596', description: 'Importância de leitura fundamentada nos primeiros passos.', category: ux_ui },
  { title: 'Dicas diretas de UI e UX (vídeo detalhado)', url: 'https://www.youtube.com/watch?v=b6BS0w4_JvI', description: 'Análise de perfis e boas orientações para LinkedIn UX.', category: ux_ui }
]

Link.create!(links)
puts "total de categorias: #{Category.count}"
puts "total de links: #{Link.count}"